config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls), #관리자페이지
    path('home/', include('home.urls')), #진료시작전페이지
    path('', main, name="main"), #완전 메인화면(첫화면)
    path('users/', include('users.urls')), #로그인, 회원가입
    path('mic/', include('mic.urls'), name='mic'),
    path('camera/', include('camera.urls'), name='cam'),
]

home/urls.py
from django.urls import path
from .views import *

app_name = "home"

urlpatterns = [
    path('select', select, name="select"), #home->views.py의 select함수를 의미
    # home/select (o) , home/select/ (x)
    path('camera', cam, name="camera"), #웹캠 링크
]

mic/urls.py
from .views import *
from django.urls import path
app_name = "mic"

urlpatterns = [
    path('mic', mic, name="mic"),
    # path('speech-to-text', speech_to_text, name='speech_to_text'),
    path('apic', apic, name='apic'),
]

mic/models.py
from django.db import models

# Create your models here.

mic/views.py
from django.shortcuts import render, redirect
from .realtimeapicall import RGspeech
import time
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.template import loader
# Create your views here.

def mic(request): #접속 시 첫 화면
    return render(request, 'mic/mic.html')

@csrf_exempt
def apic(request): #api 호출 함수
    gsp = RGspeech()
    stt = ''
    while True:
            # 음성 인식 될때까지 대기 한다.
        new_stt = gsp.getText()
        if new_stt is None:
            break
        stt += new_stt
        print(new_stt)
        print(stt)

        if "끝입니다" in stt:
            # return redirect('/home/camera')
            time.sleep((1))

    time.sleep(0.01)
        # \\break
    # time.sleep(0.01)
    return render(request, 'mic/result.html', {'stt' : stt})

mic/templates/mic/mic.html
{% extends 'base.html' %}
{% block content %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Hearo</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        function startSpeechToText() {
            $.ajax({
                url: "/mic/apic",
                type: "post",
                success: function (data) {
                    document.getElementById('stt').innerHTML = data;
                    // 재귀 호출로 계속해서 음성 인식을 수행하고 결과를 업데이트합니다.
                    startSpeechToText();
                }
            });
        }

        function stopSpeechToText() {
            // 재귀 호출을 멈추기 위해 아무 작업도 수행하지 않습니다.
        }

        function goToCameraPage() {
            window.location.href = "{% url 'home:camera' %}";
        }

<!--        function redirectToCamera() {-->
<!--            window.location.href = "{% url 'home:camera' %}";-->
<!--        }-->

<!--        // "끝입니다"가 감지되면 페이지 이동 함수 호출-->
<!--        if (document.getElementById('stt').textContent.includes('끝입니다')) {-->
<!--            redirectToCamera();-->
<!--        }-->
    </script>
    <style>
        .image-container {
            position: absolute;
            top: 50px;
            right: 10px;
        }

        .image-container img {
            max-width: 100px;
            height: auto;
            cursor: pointer;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center align-items-start vh-100">
            <div class="col-md-8 text-center">
            <br><br>
            <p class="fs-5">의료 기관의 음성 인식을 시작하겠습니다.</p>
            <p class="fs-5">아래의 "음성 인식 시작" 버튼을 눌러주세요.</p>
            <button href="javascript:void(0);" class="btn btn-primary" onclick="startSpeechToText();" style="font-size: 20px;">음성 인식 시작</button>
            <br><br><br>
            <p class="fs-4">음성 인식 결과</p>
            </div>
        </div>
    </div>

    <div id="stt"></div>

    <div class="row justify-content-center" style="margin-top: -200px;">
        <div class="col-md-5 text-center">
            <button class="btn btn-primary" onclick="redirectToCamera()" style="font-size: 20px;">다시 수어 버튼</button>
        </div>
    </div>

<!--    <div class="image-container">-->
<!--        <div style="text-align: center;">-->
<!--            <img src="/static/photography.png" alt="Photography" onclick="goToCameraPage();">-->
<!--        </div>-->
<!--        <p style="text-align: center;">카메라 전환을 원하시면 위의 아이콘을 클릭해주세요</p>-->
<!--    </div>-->

<script>
function redirectToCamera() {
  window.location.href = '/camera/camera';
}
</script>
</body>
</html>
{% endblock %}

mic/templates/mic/result.html
<!DOCTYPE html>
<html>
<head>
    <style>
        .container {
            display: flex;
            align-items: center;
        }

        .image {
            width: auto;
            height: 30px;
            margin-right: 10px;
        }

        .speech-bubble {
            position: relative;
            background-color: lightgray;
            border-radius: 20px;
            padding: 20px;
            font-size: 20px;
            margin-left: 50px;
            display: flex;
            align-items: center;
            margin-top: 10px;
        }

        .speech-bubble:after {
            content: '';
            position: absolute;
            left: 0;
            top: 50%;
            right: -20px;
            width: 0;
            height: 0;
            border: 30px solid transparent;
	        border-right-color: lightgray;
	        border-left: 0;
	        border-bottom: 0;
	        margin-top: -15px;
	        margin-left: -30px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="image">
            <img src="/static/doctorgroup.png" alt="Doctor">
        </div>
        <div class="speech-bubble">
            <p>{{ stt }}</p>
        </div>
    </div>
</body>
</html>