config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls), #관리자페이지
    path('home/', include('home.urls')), #진료시작전페이지
    path('', main, name="main"), #완전 메인화면(첫화면)
    path('users/', include('users.urls')), #로그인, 회원가입
    path('mic/', include('mic.urls'), name='mic'),
    path('camera/', include('camera.urls'), name='cam'),
]

home/urls.py
from django.urls import path
from .views import *

app_name = "home"

urlpatterns = [
    path('select', select, name="select"), #home->views.py의 select함수를 의미
    # home/select (o) , home/select/ (x)
    path('camera', cam, name="camera"), #웹캠 링크
]

mic/urls.py
from .views import *
from django.urls import path
app_name = "mic"

urlpatterns = [
    path('mic', mic, name="mic"),
    # path('speech-to-text', speech_to_text, name='speech_to_text'),
    path('apic', apic, name='apic'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

templates/base.html
<!doctype html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hearo</title>
  </head>
  <body>
    <!-- 네비게이션바 : 모든 페이지에서 공통으로 보임 -->
    {%include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 START -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 END -->
  </body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="ko">

<head>

    <meta charset="UTF-8">
    <title>HEARO</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hearo</title>
    <style>
        body {
            display: flex;
            align-items: center;
            justify-content: space-between;
            height: 100vh;
            margin: 0;
        }

        .content {
            flex: 1;
            text-align: left;
            padding-left: 400px;
        }

        .image-container {
            flex: 1;
            text-align: right;
            padding-right: 200px;
            margin-top: 20px;
        }

        .image-container img {
            width: 500px;
            height: auto; /* 자동으로 높이 조정 */
        }

        h1 {
            font-size: 50px;
            margin: 0;
        }

        .small-text {
            font-size: 14px;
            color: black;
        }

        .button-container {
            text-align: left;
            padding-left: 20px;
            margin-top: 20px;
        }

        .button-container button {
            margin: 10px;
            padding: 10px 20px;
            font-size: 20px;
            border-radius: 5px;
        }


    </style>
    <script>
        function goToSignUpPage() {
            window.location.href = "{% url 'users:signup' %}";  // 회원가입 페이지 URL로 이동
        }

        function goToSelectPage(){
            window.location.href = "{% url 'home:select' %}"
        }
    </script>
</head>
<body>
    <div class="content">
        <h1>이어로 <span class="small-text">HEARO</span></h1>
        <br>
        <form method="post" action="{% url 'main' %}">
            {% csrf_token %}
            {% include "users/form_errors.html" %}
            <div class="mb-3">
                <label for="username">사용자ID</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password">비밀번호</label>
                <input type="password" class="form-control" name="password" id="password"
                       value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary" style="padding: 10px 238px;">로그인</button>
        </form>
        <div class="button-container">
            <button onclick="goToSignUpPage()">회원가입</button>
            <br>
            <button onclick="goToSelectPage()">기능 선택하기</button>
        </div>
    </div>
    <div class="image-container">
        <img src="/static/discussion.png" alt="Image">
    </div>
</body>
</html>

templates/navbar.html
<!-- 네비게이션바 -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
      <div class="container-fluid">
          <a class="navbar-brand" href="/">Hearo</a>
          <button class="navbar-toggler" type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                      {% if user.is_authenticated %}
                      <a class="nav-link" href="{% url 'users:logout' %}">{{ user.username }} (로그아웃)</a>
                      {% else %}
                      <a class="nav-link" href="{% url 'users:login' %}">로그인</a>
                      {% endif %}
                  </li>
                  <li>
                      <!-- 로그아웃 상태에서만 회원가입이 보이도록 설정 -->
                      {% if not user.is_authenticated %}
                      <a class="nav-link" href="{% url 'users:signup' %}">회원가입</a>
                      {% endif %}
                </li>
              </ul>
          </div>
      </div>
  </nav>